---
version: 2
plan:
  project-key: WEBCO
  key: VLUIDATEPICKER
  name: webcomponent-vl-ui-datepicker

triggers:
  - polling: 130

variables:
  release_version: patch

stages:
  - Build:
      jobs:
        - Build
  - Release:
      manual: true
      jobs:
        - Release

Build:
  key: BD
  tasks:
    - clean
    - script: |
        #!/usr/env/bin bash
        set -e
        docker-compose -f test/docker-compose.yml up --exit-code-from tests
  final-tasks:
    - script: /opt/scripts/docker/stop-docker-containers.sh
  requirements:
    - REMOTE_ONLY

Release:
  key: REL
  tasks:
    - clean
    - script: |
        #!/usr/env/bin bash
        set -e
        /opt/scripts/git/git-repository-information-restore.sh
        docker run -e http_proxy=${bamboo.http_proxy} -e https_proxy=${bamboo.http_proxy} -e HTTP_PROXY=${bamboo.http_proxy} -e HTTPS_PROXY=${bamboo.http_proxy} -e GIT_REPO=${bamboo_repository_git_repositoryUrl} -e RELEASE_VERSION=${bamboo.release_version} acd-docker.repository.milieuinfo.be/milieuinfo/wc-release:1.0.0
  final-tasks:
    - script: /opt/scripts/docker/stop-docker-containers.sh
  requirements:
    - REMOTE_ONLY

---
version: 2
plan:
  key: VLUIDATEPICKER

plan-permissions:
  - groups:
      - bamboo-admin
      - bamboo-release
      - developer-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
